# fly.toml app configuration file generated for project3-autumn-voice-1509 on 2024-01-31T11:28:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project3-autumn-voice-1509'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
