# fly.toml app configuration file generated for project3-divine-lake-8105 on 2024-03-08T20:10:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project3-divine-lake-8105'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
