apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000  # Port exposed by the Service
      targetPort: 3000  # Port that the application is listening on inside the Pods
      nodePort: 30000 # Port exposed on all nodes in the cluster
  type: NodePort
