apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']  # Prometheus self-monitoring

      - job_name: 'nodejs-app'
        static_configs:
          - targets: ['nodejs-service.default.svc.cluster.local:3000']  # Service endpoint for the Node.js application
