name: Build and Push Docker Image

on:
  workflow_dispatch:  # Adjust branch name as needed

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: zinx666
          password: ${{ secrets.DOCKER_HUB_API_KEY }}
          
      - name: Build Docker Image
        run: docker build -t zinx666/mediaverse:latest .
        
      - name: Push Docker Image
        run: docker push zinx666/mediaverse:latest
