name: Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  infra:
    # terraform
    name: Terraform Init
    uses: ./.github/workflows/terraform-init.yml
    secrets: inherit
    
  format_and_plan:
    name: Format and Plan Infra
    uses: ./.github/workflows/terraform-init.yml
    secrets: inherit
    
  apply:
    name: Terraform Apply 
    uses: ./.github/workflows/apply.yml
    needs: [/]
    secrets: inherit   
