name: Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  apply:
    name: Terraform Apply 
    uses: ./.github/workflows/apply.yml
    secrets: inherit   

  destroy:
    name: Terraform Destroy
    uses: ./.github/workflows/destroy.yml
    needs: [apply]
    secrets: inherit
