name: Dispatch Jobs on Push to Main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  set-permissions:
    name: Set executable permissions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set executable permissions
        run: chmod +x ./.github/workflows/TF-AWS_login.yml

  aws-login:
    name: AWS login 
    runs-on: ubuntu-latest
    needs: [set-permissions]
    steps:
      - name: AWS login step
        run: ./.github/workflows/TF-AWS_login.yml

  terraform-init:
    name: Terraform init 
    runs-on: ubuntu-latest
    needs: [aws-login]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform init step
        run: ./.github/workflows/TF-init.yml

  terraform-plan:
    name: Terraform Plan 
    runs-on: ubuntu-latest
    needs: [terraform-init]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Terraform Plan step
        run: ./.github/workflows/TF-plan.yml
