name: Setup Terraform
on:
  push:
  pull_request:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
