name: Terraform Init
on:
  push:
  pull_request:
jobs:
  terraform_init:
    runs-on: ubuntu-latest
    needs: [checkout, setup]
    steps:
      - name: Terraform init
        run: terraform init -backend-config="bucket=${BUCKET_TF_STATE}"
