name: Terraform Destroy
on:
  push:
    branches:
      - main
jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    needs: terraform_apply
    steps:
      - name: Terraform destroy
        run: terraform destroy --auto-approve
