name: Terraform Validate
on:
  push:
  pull_request:
jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    needs: terraform_format
    steps:
      - name: Terraform validate
        run: terraform validate
