name: Terraform Plan
on:
  push:
  pull_request:
jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_validate
    steps:
      - name: Terraform plan
        run: terraform plan -no-color -input=false
