name: Terraform Format
on:
  push:
  pull_request:
jobs:
  terraform_format:
    runs-on: ubuntu-latest
    needs: terraform_init
    steps:
      - name: Terraform format
        run: terraform fmt -check
