name: Terraform Apply
on:
  push:
    branches:
      - main
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Terraform apply
        run: terraform apply --auto-approve
