name: Terraform Init

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["AWS Infrastructure Deployment"]
    types:
      - completed

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform
