name: Terraform Plan

on:
  workflow_run:
    workflows: ["Terraform Init"]
    types:
      - completed

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform
